twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/shufler_form_theme_layout.html.twig']
    globals:
        no_cover_picture: 'no_cover'
when@test:
    twig:
        strict_variables: true
