version: '3'

services:
  db:
    image: bitnami/mysql
    #command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_USER=shufler
      - MYSQL_ROOT_PASSWORD=shufler
      - MYSQL_DATABASE=shufler
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  db_data:
