services:
  db:
    image: mysql:8.0.41-debian
    #command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=shufler
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - '8025:8025'
      - '1025:1025'

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_VHOST: shufler
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  db_data:
